// <auto-generated />
namespace ServiceCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051142269_OrderIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
